language: ruby

rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0

sudo: false

before_install: gem update bundler --no-document
script: 'bundle exec rake spec'
after_success:
  - bundle exec codeclimate-test-reporter

cache: bundler
